version: "2"
exclude_patterns:
  - "bin/"
  - "data/"
  - "dev/"
  - "scripts/"
  - "vendor/"
  - ".vscode/"
  - "LICENSE"
  - "go.sum"
  - "go.mod"
  - "**/*.json"
  - "*.md"
  - ".*.yml"
  - "*.yml"
  - ".dockerignore"
  - ".gitignore"
  - "Dockerfile"
  - "Makefile"
  - "CNAME"
  - "sample.properties"
  - "CONTRIBUTORS"
plugins:
  fixme:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
